name: soccer_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.3.1
  equatable: ^2.0.5
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  http: ^0.13.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^1.1.6

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Semibold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Euclid
      fonts:
        - asset: assets/fonts/Euclid-Circular-A-Regular.ttf
        - asset: assets/fonts/Euclid-Circular-A-Bold.ttf
        - asset: assets/fonts/Euclid-Circular-A-Bold-Italic.ttf
        